### PR TITLE
Idea IdeasListItem - adding icons

### PR DESCRIPTION
**Pull request by phillimorland**

### CODE REVIEW

**Comment by phillimorland** [comment]
This is currently importing icons directly, I think it might be better to have this as a dependency but I don't know enough about it yet, also didn't know it could work like this so thats cool! :)

**Comment by khamui** [comment]
Pretty cool @phillimorland !

**Comment by khamui** [comment]
ah just saw now that you installed a new dependency `react-native-elements`. Do we need that? Or could we build our own button component which allows icons?

@phillimorland

**Comment by phillimorland** [comment]
@khamui I think we totally can, but i'm not sure if it's worth it at this point, for accessibility and ease for first concept this should be ok? I will add to the pad to look into how to make custom buttons and ensure accessibility though!

**Comment by khamui** [comment]
actually while integrating this into my code, i think it may be better to use this extra dependency. Exactly as you said because of accessiblity and also cross plattform mobile gesture touch behavior it is maybe better then inventing the wheel again. So lets use it

**Pull request merged**
