### PR TITLE
adding progressbar to ExploreListItem

### PR DESCRIPTION
**Pull request by khamui**
@Rineee and here the corresponding aplus PR:
https://github.com/liqd/adhocracy-plus/pull/1955

### CODE REVIEW

**Comment by Rineee** [comment]
@khamui Cant request review from you, but this should be ready now?

**Comment by khamui** [comment]
Nice @Rineee ! yes looks good, is the corresponding PR in aplus ready as well?

**Comment by Rineee** [comment]
> Nice @Rineee ! yes looks good, is the corresponding PR in aplus ready as well?

Gimme a second, still adding a test.. I'll tag you then!

**Comment by khamui** [comment]
very nice!

**Pull request merged**
