### PR TITLE
imageFormField: refactor to update styling, behaviours and rm permiss…

### PR DESCRIPTION
**Pull request by phillimorland**
…ions dependency//Ideas: refctor fo additional styline

### CODE REVIEW

**Comment by phillimorland** [comment]
This replaces deprecated permissions package and updates the styling for picked images

**Review by fuzzylogic2000 — APPROVED** [review]
Supercool! Looks good and works!

**Comment by fuzzylogic2000** [comment]
Oh, sorry, I've seen that it's WIP now. Shouldn't I merge?

**Comment by phillimorland** [comment]
@fuzzylogic2000 ok finished that bit

**Review by fuzzylogic2000 — APPROVED** [review]
Yeah!

**Pull request merged**
